# Generated by Django 5.2.4 on 2025-12-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fact_value', models.FloatField()),
                ('plan_value', models.FloatField()),
                ('month', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.department')),
            ],
        ),
    ]
